import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed'
import Widgets from '../components/Widgets'

export default function Home({newsResults,randomUsersResults}) {



  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className='flex min-h-screen   mx-auto '>

        {/* sidebar */}
        <Sidebar/>

        {/* Feed */}
        <Feed />

        {/* Widgets */}
        <Widgets newsResults={newsResults.articles} randomUsersResults={randomUsersResults.results} />

        {/* modal */}

      </main>
    
    </div>
  )
}


// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json
// https://randomuser.me/api/?results=30&inc=name,login,picture

export async function getServerSideProps(){
  // news api
  const newsResults = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/business/us.json').then(res=>res.json());
  
  // followers
  
  const randomUsersResults = await fetch("https://randomuser.me/api/?results=30&inc=name,login,picture").then(res=>res.json()); 
  return{
    props:{
      newsResults,
      randomUsersResults
    }
  }
}

